name: pettime_frontend
description: Projeto Flutter do PETTIME

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  # Firebase para notificações push reais
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.7
  test: ^1.24.6

flutter:
  uses-material-design: true